/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_contikios_cooja_serial2pty_LinuxPseudoTerminal */

#ifndef _Included_org_contikios_cooja_serial2pty_LinuxPseudoTerminal
#define _Included_org_contikios_cooja_serial2pty_LinuxPseudoTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_contikios_cooja_serial2pty_LinuxPseudoTerminal
 * Method:    setupMasterPt
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_contikios_cooja_serial2pty_LinuxPseudoTerminal_setupMasterPt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_contikios_cooja_serial2pty_LinuxPseudoTerminal
 * Method:    getSlavePtsName
 * Signature: (Ljava/io/FileDescriptor;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_contikios_cooja_serial2pty_LinuxPseudoTerminal_getSlavePtsName
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_contikios_cooja_serial2pty_LinuxPseudoTerminal
 * Method:    setupSlavePt
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_contikios_cooja_serial2pty_LinuxPseudoTerminal_setupSlavePt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_contikios_cooja_serial2pty_LinuxPseudoTerminal
 * Method:    closePt
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_org_contikios_cooja_serial2pty_LinuxPseudoTerminal_closePt
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
